stage1
nasssik/webix-jet pull request #1
Opened 2021-08-23 11:08 UTC by nasssik

2021-08-27 12:18 UTC, HelgaListopad requested changes
С навигацией и попапом всё хорошо, а вот с датами - не совсем. 
Если у тебя сбились даты в данных при сохранении (скорее всего, так и будет при тестах), замени файл `db.sqlite` на его исходную версию из архива и перезапусти бэк.

В дополнение к этому 

1. `yarn run lint --fix` (у меня заработал и исправил linebreak)

2. Модуль Settings должен существовать хотя бы как пустое вью, чтобы не было ошибки при попытке его открыть. 
Более сложный сценарий (тут не нужен, то лучше знать) - [отловить ошибку](https://webix.gitbook.io/webix-jet/part-ii-webix-jet-in-details/inner-events-and-error-handling#error-handling-and-debugging) открытия и перенаправить на другую страницу приложения.

2021-08-27 12:18 UTC, HelgaListopad commented on sources/models/activity.js
> +			obj.DueDate = `${dateForatting(obj.DueNewDate)} ${formatTime(obj.DueNewTime)}`;
`dateFor(m)atting` - это strToDate метод , результатом работы которого является Date object
В результате на сервер уходит такое (в то время как отправлять нужно `yyyy-mm-dd hh:ii`)
![image](https://user-images.githubusercontent.com/7587383/131124406-80e8128e-4289-409e-847e-f79e54503c0f.png)

2021-08-27 12:18 UTC, HelgaListopad commented on sources/models/activity.js
> +const dateForatting = webix.Date.strToDate("%Y-%m-%d %H:%i");
Опечатка, пропущено **m**

2021-08-27 12:18 UTC, HelgaListopad commented on sources/models/activity.js
> +const dateForatting = webix.Date.strToDate("%Y-%m-%d %H:%i");
Насколько я помню, формат даты на входе и выходе должен быть одинаковый: сервер присылает `yyyy-mm-dd hh:ii`, и то же самое должно быть сохранено.

2021-08-27 12:18 UTC, HelgaListopad commented on sources/views/contactInfo.js
> +							align: "left",
У темплейта не этого свойства (есть только у form controls). 
На практике даже там оно нужно очень редко - позиционирование можно настроить через правильный размер + spacer

2021-09-03 12:24 UTC, kullias requested changes
остается правка по поводу исходящей даты на сохранение
+ пожелания по поводу вида (скролл по горизонтали у таблицы, иконки для редактирования и удаления, выравнивание лейблов в форме)

2021-09-08 16:17 UTC, kullias approved these changes

2021-09-08 16:20 UTC, merged